---
name: Release

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  release-mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@5dafb461cea1f8b296d89297dc6de7bd0891f0d2 # v0.44.2
